- name: Deploy Pet Clinic Application
  hosts: targets
  become: yes
  tasks:
    - name: Copying application JAR to Server 2
      copy:
        src: /var/lib/jenkins/workspace/petclinic/target/spring-petclinic-3.3.0-SNAPSHOT.jar
        dest: /opt/spring-petclinic-3.3.0-SNAPSHOT.jar

    - name: Run the application
      shell: "java -jar /opt/spring-petclinic-3.3.0-SNAPSHOT.jar &"
